- name: archers
  aliases: !!set
    ? arch
    ? archers
  emoji: <:archers:521143703205576715>
- name: arrows
  aliases: !!set
    ? arr
    ? arrow
    ? arrows
  emoji: <:arrows:521143703021289493>
- name: baby-dragon
  aliases: !!set
    ? baby-dragon
    ? babyd
    ? babydragon
    ? bbd
    ? bd
    ? test
  emoji: <:babydragon:521152753138139160>
- name: balloon
  aliases: !!set
    ? balloon
    ? loon
  emoji: <:balloon:521152752366387202>
- name: bandit
  aliases: !!set
    ? band
    ? bandit
  emoji: <:bandit:521152753242734592>
- name: barbarian-barrel
  aliases: !!set
    ? barb-barrel
    ? barbarian-barrel
    ? bb
  emoji: <:barbarianbarrel:521152752810852362>
- name: barbarian-hut
  aliases: !!set
    ? barb-hut
    ? barbarian-hut
    ? barbarianhut
    ? bh
  emoji: <:barbarianhut:521143706917666837>
- name: barbarians
  aliases: !!set
    ? barb
    ? barbarians
    ? barbs
  emoji: <:barbarians:521143706301104138>
- name: bats
  aliases: !!set
    ? bat
    ? bats
  emoji: <:bats:521074863973072917>
- name: battle-healer
  aliases: !!set
    ? battle-healer
    ? battlehealer
    ? bhealer
  emoji: <:battlehealer:700272285033955378>
- name: battle-ram
  aliases: !!set
    ? battle-ram
    ? battleram
    ? br
    ? ram
  emoji: <:battleram:521143706682916909>
- name: bomb-tower
  aliases: !!set
    ? bomb-tower
    ? bombtower
    ? bt
  emoji: <:bombtower:521143705865027586>
- name: bomber
  aliases: !!set
    ? bomber
  emoji: <:bomber:521143706884112394>
- name: bowler
  aliases: !!set
    ? bowler
  emoji: <:bowler:521152753163304970>
- name: cannon
  aliases: !!set
    ? cannon
  emoji: <:cannon:521143706430996491>
- name: cannon-cart
  aliases: !!set
    ? cannon-cart
    ? cannoncart
    ? cart
    ? cc
  emoji: <:cannoncart:521152752588554250>
- name: clone
  aliases: !!set
    ? clone
  emoji: <:clone:521152752810721311>
- name: dark-prince
  aliases: !!set
    ? dank-prince
    ? dark-prince
    ? darkprince
    ? dp
  emoji: <:darkprince:521152753398054914>
- name: dart-goblin
  aliases: !!set
    ? dart-gob
    ? dart-goblin
    ? dart-gobs
    ? dartgoblin
    ? dg
  emoji: <:dartgoblin:521143706833780746>
- name: earthquake
  aliases: !!set
    ? earthquake
    ? eq
    ? quake
  emoji: <:earthquake:575323581471522839>
- name: electro-dragon
  aliases: !!set
    ? ed
    ? edrag
    ? electro-dragon
    ? electrodragon
  emoji: <:electrodragon:521152752768778250>
- name: electro-wizard
  aliases: !!set
    ? electro-wizard
    ? electrowizard
    ? ew
    ? ewiz
    ? ewizard
  emoji: <:electrowizard:521152752584491009>
- name: elite-barbarians
  aliases: !!set
    ? eb
    ? ebarb
    ? ebarbs
    ? elite-barbarians
    ? elitebarbarians
  emoji: <:elitebarbarians:521143706565345293>
- name: elixir-collector
  aliases: !!set
    ? collector
    ? ec
    ? elixir-collector
    ? elixircollector
    ? pump
  emoji: <:elixircollector:521143706292715540>
- name: elixir-golem
  aliases: !!set
    ? eg
    ? egolem
    ? elixir-golem
    ? elixirgolem
  emoji: <:elixirgolem:699106954823335956>
- name: executioner
  aliases: !!set
    ? ex
    ? exe
    ? exec
    ? executioner
  emoji: <:executioner:521152752210935810>
- name: fire-spirits
  aliases: !!set
    ? fire-spirits
    ? firespirits
    ? fs
  emoji: <:firespirits:521143706510819340>
- name: fireball
  aliases: !!set
    ? fb
    ? fireball
  emoji: <:fireball:521143706556825640>
- name: firecracker
  aliases: !!set
    ? fc
    ? firecracker
  emoji: <:firecracker:699106971646689321>
- name: fisherman
  aliases: !!set
    ? fish
    ? fisher
    ? fisherman
    ? fishman
    ? fman
  emoji: <:fisherman:596463067441790976>
- name: flying-machine
  aliases: !!set
    ? fly
    ? flying-machine
    ? flyingmachine
    ? fm
    ? machine
  emoji: <:flyingmachine:521143706515013644>
- name: freeze
  aliases: !!set
    ? freeze
  emoji: <:freeze:521152752898801702>
- name: furnace
  aliases: !!set
    ? furnace
  emoji: <:furnace:521143706531921930>
- name: giant
  aliases: !!set
    ? giant
  emoji: <:giant:521143706863271985>
- name: giant-skeleton
  aliases: !!set
    ? giant-skeleton
    ? giantskeleton
    ? gs
  emoji: <:giantskeleton:521152753184014346>
- name: giant-snowball
  aliases: !!set
    ? giant-snowball
    ? giantsnowball
    ? gsb
    ? snow
    ? snowball
  emoji: <:giantsnowball:521143705961234432>
- name: goblin-barrel
  aliases: !!set
    ? barrel
    ? gb
    ? gob-barrel
    ? goblin-barrel
    ? goblinbarrel
  emoji: <:goblinbarrel:521149877170733097>
- name: goblin-cage
  aliases: !!set
    ? cage
    ? gc
    ? gob-cage
    ? goblin-cage
    ? goblincage
  emoji: <:goblincage:587052058830700584>
- name: goblin-gang
  aliases: !!set
    ? gg
    ? gob-gang
    ? goblin-gang
    ? goblingang
  emoji: <:goblingang:521143707781562408>
- name: goblin-giant
  aliases: !!set
    ? ggi
    ? ggiant
    ? goblin-giant
    ? goblingiant
  emoji: <:goblingiant:521152753003659265>
- name: goblin-hut
  aliases: !!set
    ? gh
    ? gob-hut
    ? gobhut
    ? goblin-hut
    ? goblinhut
  emoji: <:goblinhut:521143707114668043>
- name: goblins
  aliases: !!set
    ? gob
    ? goblins
    ? gobs
    ? stab-gob
    ? stab-gobs
  emoji: <:goblins:521143706695237653>
- name: golem
  aliases: !!set
    ? golem
  emoji: <:golem:521152752655663130>
- name: graveyard
  aliases: !!set
    ? graveyard
    ? gy
    ? skillyard
  emoji: <:graveyard:521152752395747331>
- name: guards
  aliases: !!set
    ? guards
  emoji: <:guards:521152752651599882>
- name: heal-spirit
  aliases: !!set
    ? heal
    ? heal-spirit
    ? healspirit
    ? hs
  emoji: <:healspirit:699106320367747093>
- name: hog-rider
  aliases: !!set
    ? hog
    ? hog-rider
    ? hogrider
  emoji: <:hogrider:521143707815247888>
- name: hunter
  aliases: !!set
    ? htr
    ? hu
    ? hunter
  emoji: <:hunter:521152752856858644>
- name: ice-golem
  aliases: !!set
    ? ice-golem
    ? icegolem
    ? ig
  emoji: <:icegolem:521143707429502978>
- name: ice-spirit
  aliases: !!set
    ? ice-spirit
    ? icespirit
    ? is
  emoji: <:icespirit:521143706825523200>
- name: ice-wizard
  aliases: !!set
    ? ice-wiz
    ? ice-wizard
    ? icewizard
    ? iw
    ? iwiz
  emoji: <:icewizard:521152752370581525>
- name: inferno-dragon
  aliases: !!set
    ? id
    ? inferno-dragon
    ? infernodragon
  emoji: <:infernodragon:521152753104584704>
- name: inferno-tower
  aliases: !!set
    ? inferno
    ? inferno-tower
    ? infernotower
    ? it
  emoji: <:infernotower:521143706909278209>
- name: knight
  aliases: !!set
    ? knight
  emoji: <:knight:521143707714584579>
- name: lava-hound
  aliases: !!set
    ? hound
    ? lava
    ? lava-hound
    ? lavahound
    ? lh
  emoji: <:lavahound:521152752726966277>
- name: lightning
  aliases: !!set
    ? lightning
  emoji: <:lightning:521152752265592843>
- name: lumberjack
  aliases: !!set
    ? lj
    ? lumberjack
  emoji: <:lumberjack:521152753142202368>
- name: magic-archer
  aliases: !!set
    ? ma
    ? magic-archer
    ? magicarcher
  emoji: <:magicarcher:521152752831954958>
- name: mega-knight
  aliases: !!set
    ? mega-knight
    ? megaknight
    ? mk
    ? mknight
  emoji: <:megaknight:521152752836149316>
- name: mega-minion
  aliases: !!set
    ? mega
    ? mega-minion
    ? megaminion
    ? meta-minion
    ? mm
  emoji: <:megaminion:521143707789950976>
- name: miner
  aliases: !!set
    ? miner
  emoji: <:miner:521152752769040386>
- name: mini-pekka
  aliases: !!set
    ? mini-p
    ? mini-pekka
    ? minip
    ? minipekka
    ? mp
  emoji: <:minipekka:521143707777630218>
- name: minion-horde
  aliases: !!set
    ? horde
    ? mh
    ? minion-horde
    ? minionhorde
  emoji: <:minionhorde:521143706783449103>
- name: minions
  aliases: !!set
    ? minions
  emoji: <:minions:521143707370782721>
- name: mirror
  aliases: !!set
    ? mirror
  emoji: <:mirror:521152748700434435>
- name: mortar
  aliases: !!set
    ? mortar
  emoji: <:mortar:521143707232370688>
- name: musketeer
  aliases: !!set
    ? 1m
    ? musk
    ? musketeer
    ? musky
  emoji: <:musketeer:521143707341160459>
- name: night-witch
  aliases: !!set
    ? night-witch
    ? nightwitch
    ? nw
    ? nwitch
  emoji: <:nightwitch:521152752785555479>
- name: pekka
  aliases: !!set
    ? pekka
  emoji: <:pekka:521152752491954179>
- name: poison
  aliases: !!set
    ? poison
  emoji: <:poison:521152753041408003>
- name: prince
  aliases: !!set
    ? prince
  emoji: <:prince:521152752991207427>
- name: princess
  aliases: !!set
    ? princess
  emoji: <:princess:521152752542416897>
- name: rage
  aliases: !!set
    ? rage
  emoji: <:rage:521152752303472671>
- name: ram-rider
  aliases: !!set
    ? ram-rider
    ? ramrider
  emoji: <:ramrider:526464336647028757>
- name: rascals
  aliases: !!set
    ? r
    ? ras
    ? rascals
  emoji: <:rascals:521143707215593473>
- name: rocket
  aliases: !!set
    ? rocket
  emoji: <:rocket:521143707362131995>
- name: royal-delivery
  aliases: !!set
    ? delivery
    ? rd
    ? royal-delivery
    ? royaldelivery
  emoji: <:royaldelivery:699106990684897311>
- name: royal-ghost
  aliases: !!set
    ? ghost
    ? royal-ghost
    ? royalghost
  emoji: <:royalghost:521152752798400512>
- name: royal-giant
  aliases: !!set
    ? rg
    ? rgg
    ? royal-giant
    ? royalgiant
  emoji: <:royalgiant:521143707077181440>
- name: royal-hogs
  aliases: !!set
    ? rh
    ? royal-hog
    ? royal-hogs
    ? royalhog
    ? royalhogs
  emoji: <:royalhogs:521143707240759307>
- name: royal-recruits
  aliases: !!set
    ? royal-recruits
    ? royalrecruits
    ? rr
  emoji: <:royalrecruits:521143707127382023>
- name: skeleton-army
  aliases: !!set
    ? sa
    ? skarmy
    ? skeleton-army
    ? skeletonarmy
  emoji: <:skeletonarmy:521152752324313098>
- name: skeleton-barrel
  aliases: !!set
    ? sb
    ? sbarrel
    ? skeleton-barrel
    ? skeletonbarrel
  emoji: <:skeletonbarrel:521143707068792834>
- name: skeletons
  aliases: !!set
    ? sk
    ? skele
    ? skeletons
  emoji: <:skeletons:521143707433435137>
- name: sparky
  aliases: !!set
    ? sparky
  emoji: <:sparky:521152753259511829>
- name: spear-goblins
  aliases: !!set
    ? sg
    ? sgob
    ? sgobs
    ? spear
    ? spear-gob
    ? spear-goblins
    ? spear-gobs
    ? speargoblins
    ? speargobs
  emoji: <:speargoblins:521143707555332107>
- name: tesla
  aliases: !!set
    ? tesla
  emoji: <:tesla:521143707001421870>
- name: the-log
  aliases: !!set
    ? log
    ? the-log
    ? thelog
  emoji: <:thelog:521152752915709952>
- name: three-musketeers
  aliases: !!set
    ? 3m
    ? 3musk
    ? 3musks
    ? muskies
    ? three-musketeers
    ? threemusketeers
  emoji: <:threemusketeers:521143707362394122>
- name: tombstone
  aliases: !!set
    ? tombstone
    ? ts
  emoji: <:tombstone:521143706838106132>
- name: tornado
  aliases: !!set
    ? nado
    ? tornado
  emoji: <:tornado:521152752324444176>
- name: valkyrie
  aliases: !!set
    ? valk
    ? valkyrie
  emoji: <:valkyrie:521143707915780106>
- name: wall-breakers
  aliases: !!set
    ? wall-breaker
    ? wall-breakers
    ? wallbreakers
    ? wb
  emoji: <:wallbreakers:546436582106988544>
- name: witch
  aliases: !!set
    ? witch
  emoji: <:witch:521152752559325207>
- name: wizard
  aliases: !!set
    ? wiz
    ? wizard
  emoji: <:wizard:521143707689549834>
- name: x-bow
  aliases: !!set
    ? x-bow
    ? xbow
  emoji: <:xbow:521152752970366987>
- name: zap
  aliases: !!set
    ? zap
  emoji: <:zap:521143707408400403>
- name: zappies
  aliases: !!set
    ? zappies
    ? zp
  emoji: <:zappies:521143707236433920>
